nacos_host: localhost:8848
nacos_namespace: 59656ea3-0252-4b9c-b9d2-3ae3eab5f631
server:
  port: 8338
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: @spring.profiles.name@
  profiles:
    active: @spring.profiles.active@
  #目前不需要指定配置
  #profiles:
  #  active: bootstrap-dev
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_host}
        namespace: ${nacos_namespace}
        metadata:
          version: @system.version@
      config:
        server-addr: ${nacos_host}
        namespace: ${nacos_namespace}
        file-extension: "yaml"
  config:
    import:
      - optional:nacos:theta-example-consumer.yaml  # 监听 DEFAULT_GROUP:theta-example-server.yaml