server:
  port: 8338
spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  shardingsphere:
    datasource:
      ds0:
        url: jdbc:mysql://rm-2zenxb8io2rv7tunk.mysql.rds.aliyuncs.com:3306/isv_prodali?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: isv
        password: ENC(CDrlqCI+N0PKPJjikebD2GUqQrYSHob4)
  application:
    name: @spring.profiles.name@
  profiles:
    active: @spring.profiles.active@
theta:
  sequence:
    available: true
    sequenceConfigs:
      - id: myCompositeString
        type: compositeString
        segmentConfigs:
          - id: date
            type: dateSegment
            args: {pattern: 'yyyyMMddHHmmss'}
          - id: db
            type: dbNumberSegment
            args: {id: 'myDbNumberSegment', maxSequenceValue: '9999999999', length: '10',step: '1000'}
          - id: type
            type: fixedStringSegment
            args: {segmentString: 'THETA'}
            # 这里可以通过数据库进行Hash
          - id: databaseIndex
            type: hashSegment
            args: {length: '2', defaultMod: '2', hashField: '2'}
            # 这里可以通过表下表进行索引Hash
          - id: tableIndex
            type: hashSegment
            args: {length: '3', defaultMod: '128', hashField: '128'}
            # 当前应用的节点编号
          - id: nodeNo
            type: fixedStringSegment
            args: {propertyName: 'nodeNo', length: '1', segmentString: '1'}
            # 生产一个6位随机数
          - id: random
            type: randomStringSegment
            args: {length: '6'}
