version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: theta_my_sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/logs/mysql/data:/var/lib/mysql/
      - ./mysql/data/logs/mysql/my.cnf:/etc/my.cnf
      - ./mysql/data/logs/mysql/init:/docker-entrypoint-initdb.d/
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data/logs/conf:/etc/redis/
      - ./redis/data/logs/data:/data
      - ./redis/data/logs/log/:/usr/local/redis/log/
  #nameserver
  namesrv:
    image: foxiswho/rocketmq:4.8.0
    container_name: cluster_rmqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - /usr/local/server/rocketmq_cluster/data_namesrv/namesrv/logs:/root/logs
      - /usr/local/server/rocketmq/data_namesrv/namesrv/store:/root/store
    command: sh mqnamesrv
  #broker1
  broker1:
    image: foxiswho/rocketmq:4.8.0
    container_name: cluster_rmqbroker1
    links:
      - namesrv
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./rocketmq/config/logs/:/root/logs
      - ./rocketmq/config/store/:/root/store
      - ./rocketmq/config/broker-1.conf/broker.conf:/opt/rocketmq-4.8.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.8.0/conf/broker.conf
  #broker2
  broker2:
    image: foxiswho/rocketmq:4.8.0
    container_name: cluster_rmqbroker2
    links:
      - namesrv
    ports:
      - "10929:10909"
      - "10931:10911"
      - "10932:10912"
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./rocketmq/config/logs/:/root/logs
      - ./rocketmq/config/store/:/root/store
      - ./rocketmq/config/broker-2.conf/broker.conf:/opt/rocketmq-4.8.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.8.0/conf/broker.conf
  rmq_theta_console:
    image: styletang/rocketmq-console-ng:1.0.0
    container_name: rmqconsole
    links:
      - namesrv
      - broker1
      - broker2
    ports:
      - "8180:8080"
    environment:
      JAVA_OPTS: "-Drocketmq.config.namesrvAddr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
networks:
  local_network:
    driver: bridge
