version: '3.5'
services:
  rmqnamesrv-a:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
      - ./config/logs/nameserver-a:/root/logs
      - ./config/store/nameserver-a:/root/store
    command: sh mqnamesrv
    networks:
      rmq:
        aliases:
          - rmqnamesrv-a

  rmqnamesrv-b:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqnamesrv-b
    ports:
      - 9877:9876
    volumes:
      - ./logs/nameserver-b:/root/store
      - ./logs/nameserver-b:/root/logs
    command: sh mqnamesrv
    networks:
      rmq:
        aliases:
          - rmqnamesrv-b

  rmqbroker-a:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker-a
    ports:
      - 10911:10911
    volumes:
      - ./config/broker-a/master/logs:/root/logs
      - ./config/broker-a/master/store/broker-a/store:/root/store
      - ./config/broker-a/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-a

  rmqbroker-a-s:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker-a-s
    ports:
      - 10912:10911
    volumes:
      - ./config/broker-a/slave/logs:/root/logs
      - ./config/broker-a/slave/store/broker-a/store:/root/store
      - ./config/broker-a/broker-s.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-a-s

  rmqbroker-b:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker-b
    ports:
      - 10913:10911
    volumes:
      - ./config/broker-b/master/logs:/root/logs
      - ./config/broker-b/master/store/broker-a/store:/root/store
      - ./config/broker-b/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-b

  rmqbroker-b-s:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker-b-s
    ports:
      - 10914:10911
    volumes:
      - ./config/broker-b/slave/logs:/root/logs
      - ./config/broker-b/slave/store/broker-a/store:/root/store
      - ./config/broker-b/broker-s.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-b-s

  rmqconsole:
    image: pangliang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rmqnamesrv-a:9876;rmqnamesrv-b:9877 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      rmq:
        aliases:
          - rmqconsole

# 自定义网络
networks:
  rmq:
    name: rmq
    driver: bridge
