version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/logs/conf:/etc/redis/
      - ./data/logs/data:/data
      - ./data/logs/log/:/usr/local/redis/log/
networks:
  local_network:
    driver: bridge
